services:
  codesandbox-api:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./temp:/app/temp
    # environment:
    #   - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    networks:
      - moodle-network

networks:
  moodle-network:
    external: true
    name: moodle-network