site_name: Moodle Docs
docs_dir: _docs
plugins:
  - mermaid2
nav:
  - Home: index.md
  - Dir structure: directory_structure.md
  - Rendering: rendering.md
  - Database:
    - Core tables: core_db_tables.md
    - All tables: moodle_database_tables_overview.md
    - schema.sql: schema.md
  - Asset management:
      Legacy: legacy_asset_management.md
      New: assets.md
  - New features:
    - 1. GitHub OAuth: features/github-oauth/README.md
    - 2. API: features/api/README.md
    - 3. Code sandbox: features/code-sandbox/README.md
    - 4. Markdown documents: features/markdown-documents/README.md
    - 5. Syntax highlighting: features/syntax-highlighting/README.md
    - 6. Modernized React UI: features/modernized-frontend/README.md
